name: Docker Build and Push

on:
  push:
    branches:
      - backend_yrlmanoharreddy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        run: docker --version

      - name: Build Admin Module Docker image
        run: |
          cd backend/admin-module
          docker build -t yrlmanoharreddymeda/yrl-admin-module .

      - name: Build Donor Module Docker image
        run: |
          cd backend/donor-module
          docker build -t yrlmanoharreddymeda/yrl-donor-module .

      - name: Log in to Docker Hub
        run: docker login -u yrlmanoharreddymeda -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Admin Module Docker image
        run: docker push yrlmanoharreddymeda/yrl-admin-module
      
      - name: Push Donor Module Docker image
        run: docker push yrlmanoharreddymeda/yrl-donor-module

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run Docker containers
        run: |
          docker-compose up -d
